//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string Size { get; set; }
        public Nullable<System.DateTime> DateItems { get; set; }
    }
}
